### ISSUE TITLE
bug: courses with multiple entries for time not processed correctly

### ISSUE THREAD

**Issue by ZeWaka** [QikLiang/UP-Schedule-Planer#5]
Courses that have multiple entries for their time are not accounted for.

Example: `Calculus II - 41316 - MTH 202 - E` in Spring 2019

![chrome_2018-11-13_12-31-22](https://user-images.githubusercontent.com/4741640/48441332-17eaff00-e740-11e8-981b-eabb939b0a2a.png)

There are[ two entries](https://selfserve-db.up.edu/prd/bwckschd.p_disp_listcrse?term_in=201902&subj_in=MTH&crse_in=202&crn_in=41316) in the time slot for the class. However, the program only parses the first entry.

![java_2018-11-13_12-32-16](https://user-images.githubusercontent.com/4741640/48441362-2afdcf00-e740-11e8-895b-b7309c47dc29.png)

I believe this can be resolved around the line: [Network.java:176](https://github.com/QikLiang/UP-Schedule-Planer/blob/4697248208fcfd5dd2011fb129db70a61139cea3/src/main/java/core/Network.java#L176)

**Comment by QikLiang** [comment]
Hey! Not only did you submit a bug report, you actually read my code! I am so touched. Report fixed and closed.
